### ISSUE TITLE
ANMN_NRS_CTD_PROFILES harvester failing on new files

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#182]
Failing to harvest 4 recently published files. Messages in console.log look like this:

    In finally block
    Exception while processing /mnt/imos-t3/IMOS/opendap/ANMN/NRS/NRSROT/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKOSTUZ_20100520T020500Z_NRSROT_FV01_3015.0-1-SBE19plus-45_C-20140130T091925Z.nc
    java.lang.NullPointerException
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.iDeletedResources_1Process(DataHarvest.java:1477)
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.iPostgresqlDbUpdate_1Process(DataHarvest.java:1326)
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.runJobInTOS(DataHarvest.java:3698)
        at anmn_nrs_ctd_profiles.dataharvest_0_1.DataHarvest.runJob(DataHarvest.java:3526)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.tRunJob_2Process(ANMN_NRS_CTD_PROFILES_harvester.java:1319)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.tRunJob_1Process(ANMN_NRS_CTD_PROFILES_harvester.java:1202)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.runJobInTOS(ANMN_NRS_CTD_PROFILES_harvester.java:3281)
        at anmn_nrs_ctd_profiles.anmn_nrs_ctd_profiles_harvester_0_1.ANMN_NRS_CTD_PROFILES_harvester.main(ANMN_NRS_CTD_PROFILES_harvester.java:3085)

The files exist, have the same permissions as all the other files in the directory, and I can't see anything obviously wrong with them. I've seen this `NullPointerException` error before, but I can't remember what the problem was.

**Comment by mhidas** [comment]
This is a duplicate of https://github.com/aodn/content/issues/80
