### ISSUE TITLE
ARGO out of memory

### ISSUE THREAD

**Issue by ggalibert** [aodn/harvesters#263]
Even after increasing the Java heap space to 4Gb, still facing a memory issue on 14-nsp :

```begin;2015-08-08 20:20:27+10:00
INFO 8/08/15 8:20 PM:liquibase: Successfully acquired change log lock
INFO 8/08/15 8:20 PM:liquibase: Reading from argo.databasechangelog
INFO 8/08/15 8:20 PM:liquibase: Reading from argo.databasechangelog
INFO 8/08/15 8:20 PM:liquibase: Successfully released change log lock
Exception in thread "main" java.lang.Error: java.lang.OutOfMemoryError: Java heap space
        at argo.argo_harvester_0_1.Argo_harvester.iIndexFiles_1_iFilesProcess(Argo_harvester.java:2544)
        at argo.argo_harvester_0_1.Argo_harvester.runJobInTOS(Argo_harvester.java:4286)
        at argo.argo_harvester_0_1.Argo_harvester.main(Argo_harvester.java:4086)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2245)
        at java.util.Arrays.copyOf(Arrays.java:2219)
        at java.util.ArrayList.toArray(ArrayList.java:358)
        at java.util.Collections.sort(Collections.java:154)
        at argo.argo_harvester_0_1.Argo_harvester.iIndexFiles_1_iFilesProcess(Argo_harvester.java:2325)
        ... 2 more
finish;2015-08-08 20:54:28+10:00 34 minutes```

**Comment by xhoenner** [comment]
Thanks for reporting that @ggalibert, I already had documented that the change I made didn't fix the harvester in https://github.com/aodn/content/issues/123.
