### ISSUE TITLE
SOOP_AUSCPR: iUpdateSpatialExtent fails

### ISSUE THREAD

**Issue by mhidas** [aodn/harvesters#284]
```
* iUpdateSpatialExtent - updating uuid 'c1344979-f701-0916-e044-00144f7bc0f4' from soop_auscpr.phyto.geom using 1 degree resolution
Exception in component iUpdateSpatialExtent_1
it.geosolutions.geonetwork.exception.GNServerException: Error updating metadata in GeoNetwork (HTTP code 400)
        at it.geosolutions.geonetwork.op.GNMetadataUpdate.gnUpdateMetadata(GNMetadataUpdate.java:130)
        at it.geosolutions.geonetwork.op.GNMetadataUpdate.update(GNMetadataUpdate.java:69)
        at it.geosolutions.geonetwork.GNClient.updateMetadata(GNClient.java:137)
        at soop_auscpr.auscp_phyto_taxon_changelog_harvest_0_1.auscp_phyto_taxon_changelog_harvest.iUpdateSpatialExtent_1Process(auscp_phyto_taxon_changelog_harvest.java:1436)
        at soop_auscpr.auscp_phyto_taxon_changelog_harvest_0_1.auscp_phyto_taxon_changelog_harvest.tPostgresqlClose_1Process(auscp_phyto_taxon_changelog_harvest.java:1225)
        at soop_auscpr.auscp_phyto_taxon_changelog_harvest_0_1.auscp_phyto_taxon_changelog_harvest.tPostjob_1Process(auscp_phyto_taxon_changelog_harvest.java:1122)
        at soop_auscpr.auscp_phyto_taxon_changelog_harvest_0_1.auscp_phyto_taxon_changelog_harvest.runJobInTOS(auscp_phyto_taxon_changelog_harvest.java:3294)
        at soop_auscpr.auscp_phyto_taxon_changelog_harvest_0_1.auscp_phyto_taxon_changelog_harvest.runJob(auscp_phyto_taxon_changelog_harvest.java:3113)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.tRunJob_1Process(phyto_harvest.java:1158)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.tPostgresqlCommit_1Process(phyto_harvest.java:1032)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.sWfsInput_1_GIProcess(phyto_harvest.java:4065)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.iPostgresqlDbUpdate_1Process(phyto_harvest.java:930)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.tPostgresqlConnection_1Process(phyto_harvest.java:711)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.iIncludeSdiLibraries_1Process(phyto_harvest.java:593)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.runJobInTOS(phyto_harvest.java:4319)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.runJob(phyto_harvest.java:4150)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.tRunJob_4Process(SOOP_AUSCPR_harvester.java:1430)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.runJobInTOS(SOOP_AUSCPR_harvester.java:3430)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.main(SOOP_AUSCPR_harvester.java:3197)
Exception in component tRunJob_1
java.lang.RuntimeException: Child job running failed
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.tRunJob_1Process(phyto_harvest.java:1169)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.tPostgresqlCommit_1Process(phyto_harvest.java:1032)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.sWfsInput_1_GIProcess(phyto_harvest.java:4065)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.iPostgresqlDbUpdate_1Process(phyto_harvest.java:930)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.tPostgresqlConnection_1Process(phyto_harvest.java:711)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.iIncludeSdiLibraries_1Process(phyto_harvest.java:593)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.runJobInTOS(phyto_harvest.java:4319)
        at soop_auscpr.phyto_harvest_0_1.phyto_harvest.runJob(phyto_harvest.java:4150)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.tRunJob_4Process(SOOP_AUSCPR_harvester.java:1430)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.runJobInTOS(SOOP_AUSCPR_harvester.java:3430)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.main(SOOP_AUSCPR_harvester.java:3197)
Exception in component tRunJob_4
java.lang.RuntimeException: Child job running failed
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.tRunJob_4Process(SOOP_AUSCPR_harvester.java:1441)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.runJobInTOS(SOOP_AUSCPR_harvester.java:3430)
        at soop_auscpr.soop_auscpr_harvester_0_1.SOOP_AUSCPR_harvester.main(SOOP_AUSCPR_harvester.java:3197)
Start of try block
tempFile_cid /tmp/talend-temp-3528746080061226221/changelog.xml
```

**Comment by danfruehauf** [comment]
If this is from yesterday (2/9/2015) - the SOOP_AUSCPR metadata record was buggered in prod and probably any update would have failed because of that.

**Comment by mhidas** [comment]
@danfruehauf Do we know what was wrong with the metadata record?

Looks ok now and the harvester ran fine last night.

**Comment by danfruehauf** [comment]
Something about uploading a thumbnail and completely breaking the record. @jonescc can maybe provide more information.

**Comment by jonescc** [comment]
@atkinsn uploaded a thumbnail to the record which for some reason broke geonetworks parsing of the record.  The record had to be deleted and the previous version imported.  Took a day or so to fix this, so the harvester fell over in the meantime.

**Comment by mhidas** [comment]
Thanks @jonescc . So we can safely conclude this is not a harvester issue.
