### ISSUE TITLE
AATAMS_ACOUSTIC_REPORTING running out of space

### ISSUE THREAD

**Issue by xhoenner** [aodn/harvesters#409]
Currently happening on 10-aws but regularly occurs also on 14-nsp. Copy of the logs below, corresponds to the process that copies the content of the detection table:

```
Exception in component tPostgresqlInput_11
org.postgresql.util.PSQLException: ERROR: could not write to hash-join temporary file: No space left on device
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_11Process(Copy_Tables.java:11509)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_10Process(Copy_Tables.java:11085)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_9Process(Copy_Tables.java:10449)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_8Process(Copy_Tables.java:9773)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_7Process(Copy_Tables.java:9104)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_6Process(Copy_Tables.java:8357)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_5Process(Copy_Tables.java:7708)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_4Process(Copy_Tables.java:6988)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_3Process(Copy_Tables.java:6286)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_2Process(Copy_Tables.java:5671)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_1Process(Copy_Tables.java:4800)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_13Process(Copy_Tables.java:4198)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_14Process(Copy_Tables.java:3542)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_15Process(Copy_Tables.java:2933)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_16Process(Copy_Tables.java:2324)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlInput_17Process(Copy_Tables.java:1715)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlConnection_3Process(Copy_Tables.java:1025)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.tPostgresqlConnection_1Process(Copy_Tables.java:896)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.runJobInTOS(Copy_Tables.java:13715)
        at aatams_acoustic_reporting.copy_tables_0_1.Copy_Tables.runJob(Copy_Tables.java:13566)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_1Process(aatams_acoustic_harvester.java:1988)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.iPostgresqlDbUpdate_1Process(aatams_acoustic_harvester.java:1868)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.runJobInTOS(aatams_acoustic_harvester.java:4309)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.main(aatams_acoustic_harvester.java:4101)
Exception in component tRunJob_1
java.lang.RuntimeException: Child job running failed
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.tRunJob_1Process(aatams_acoustic_harvester.java:1999)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.iPostgresqlDbUpdate_1Process(aatams_acoustic_harvester.java:1868)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.runJobInTOS(aatams_acoustic_harvester.java:4309)
        at aatams_acoustic_reporting.aatams_acoustic_harvester_0_1.aatams_acoustic_harvester.main(aatams_acoustic_harvester.java:4101)

```

**Comment by julian1** [comment]
Issue looks to be on aatams instance, not dbprod or 10-aws.
```
root@3-aws-syd:~$ grep space /var/log/postgresql/postgresql-9.4-aatams.log.1
2016-05-12 08:08:13 GMT 52.64.146.138 aatams_acoustic aatams3 1278 53100ERROR:  could not write to hash-join temporary file: No space left on device
2016-05-12 08:08:13 GMT 103.6.252.109 aatams_acoustic aatams3 1339 53100ERROR:  could not write to hash-join temporary file: No space left on device
```
```
root@3-aws-syd:~$ df -h | grep db
/dev/mapper/db--1-1   99G   64G   31G  68% /mnt/db/1
```

**Comment by lwgordonimos** [comment]
1. Does the query legitimately need a temp table of this size? 
2. If yes, best practice suggests that there should (at least) be a separate partition for temp tablespace, which is how I've always provisioned DBs in the past:
https://wiki.postgresql.org/wiki/Simple_Configuration_Recommendation

Having everything on one partition like this could get nasty if writes to the transaction log are blocked by a full disk.

**Comment by julian1** [comment]
> Does the query legitimately need a temp table of this size? 

@xhoenner is in a better position to answer, but I believe so - since it's a full db extract for reporting. In the past we had a replicated master/reporting solution to separate needs and avoid having to write harvesters.

> If yes, best practice suggests that there should (at least) be a separate partition for temp tablespace,

Separating temp query processing resources from the critical WAL stuff sounds great!

**Comment by xhoenner** [comment]
> Does the query legitimately need a temp table of this size?

Yes it does indeed as the content of the whole table is needed for reporting purposes.

**Comment by lwgordonimos** [comment]
Resolved by https://github.com/aodn/chef/pull/306
