### ISSUE TITLE
getglobalattribute psql function not exist

### ISSUE THREAD

**Issue by lbesnard** [aodn/harvesters#429]
Doing some testing on my pobox, I ran into this new issue :

```
SEVERE 7/12/16 1:40 PM:liquibase: Change Set changelog.xml::add_toolbox_input_file_column::talend failed.  Error: Error executing SQL UPDATE file_metadata m
          SET toolbox_input_file = getglobalattribute(file_id, 'toolbox_input_file'): ERROR: function getglobalattribute(bigint, unknown) does not exist
liquibase.exception.DatabaseException: Error executing SQL UPDATE file_metadata m
          SET toolbox_input_file = getglobalattribute(file_id, 'toolbox_input_file'): ERROR: function getglobalattribute(bigint, unknown) does not exist
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at anmn_metadata.anmn_metadata_harvester_0_1.ANMN_metadata_harvester.iPostgresqlDbUpdate_1Process(ANMN_metadata_harvester.java:1393)
        at anmn_metadata.anmn_metadata_harvester_0_1.ANMN_metadata_harvester.iUpdateIndex_2Process(ANMN_metadata_harvester.java:1091)
        at anmn_metadata.anmn_metadata_harvester_0_1.ANMN_metadata_harvester.runJobInTOS(ANMN_metadata_harvester.java:4012)
        at anmn_metadata.anmn_metadata_harvester_0_1.ANMN_metadata_harvester.main(ANMN_metadata_harvester.java:3840)
Caused by: org.postgresql.util.PSQLException: ERROR: function getglobalattribute(bigint, unknown) does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1592)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1327)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:192)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:336)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:328)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 11 more
```

does this ring a bell to you @mhidas @jonescc

**Comment by mhidas** [comment]
Ah.. I think I can see what's happening. There's a subjob that defines the `getglobalattribute` functions, but it runs *after* the main liquibase that sets up the schema. This was fine initially, but then I added a column and needed to populate it using the `getglobalattribute` function. This didn't break it for me because I only ran it on an existing schema, but running it on a new empty schema results in the error you're seeing.

I think I can fix that by reversing the order of those two subjobs. As it happens I'm just working on that harvester, so I'll do that now.
