### ISSUE TITLE
AATAMS_SATTAG_DM - error with tJDBCinput component

### ISSUE THREAD

**Issue by xhoenner** [aodn/harvesters#497]
The following error killed the harvester on 10aws, see /mnt/ebs/log/data-services/AATAMS_SATTAG_DM/tmp.MA224LC5vq.20170218-000037.log.1

Looks like the harvester can't deal with data in the 'ctd' table found in the 'ct133.mdb' file, however, I've been able to read its content successfully in R. 

```bash
Exception in component tJDBCInput_4
h2.jdbc.JdbcSQLException: Data conversion error converting "4,10,14,20,26,28,30,32,36,40,48,50,54,66,68,74" [90021-147]
        at h2.message.DbException.a(Unknown Source)
        at h2.message.DbException.get(Unknown Source)
        at h2.value.Value.convertTo(Unknown Source)
        at h2.value.Value.getFloat(Unknown Source)
        at h2.jdbc.JdbcResultSet.getFloat(Unknown Source)
        at aatams_sattag_dm.harvest_ctddata_0_1.Harvest_CTDdata.tJDBCInput_4Process(Harvest_CTDdata.java:6732)
        at aatams_sattag_dm.harvest_ctddata_0_1.Harvest_CTDdata.tPostgresqlRow_1Process(Harvest_CTDdata.java:889)
        at aatams_sattag_dm.harvest_ctddata_0_1.Harvest_CTDdata.tPostgresqlConnection_1Process(Harvest_CTDdata.java:760)
        at aatams_sattag_dm.harvest_ctddata_0_1.Harvest_CTDdata.iIncludeSdiLibraries_1Process(Harvest_CTDdata.java:637)
        at aatams_sattag_dm.harvest_ctddata_0_1.Harvest_CTDdata.runJobInTOS(Harvest_CTDdata.java:11213)
        at aatams_sattag_dm.harvest_ctddata_0_1.Harvest_CTDdata.runJob(Harvest_CTDdata.java:11060)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iNewOrModifiedFileList_1Process(aatams_sattag_dm_harvester.java:2664)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iDeletedFileList_1Process(aatams_sattag_dm_harvester.java:2439)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iPostgresqlDbUpdate_1Process(aatams_sattag_dm_harvester.java:2152)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iUpdateIndex_1Process(aatams_sattag_dm_harvester.java:1463)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.tPostgresqlConnection_1Process(aatams_sattag_dm_harvester.java:1344)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.runJobInTOS(aatams_sattag_dm_harvester.java:5519)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.main(aatams_sattag_dm_harvester.java:5307)
Caused by: java.lang.NumberFormatException: For input string: "4,10,14,20,26,28,30,32,36,40,48,50,54,66,68,74"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
        at java.lang.Float.parseFloat(Float.java:452)
        ... 16 more
Exception in component tRunJob_1
java.lang.RuntimeException: Child job running failed
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iNewOrModifiedFileList_1Process(aatams_sattag_dm_harvester.java:2675)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iDeletedFileList_1Process(aatams_sattag_dm_harvester.java:2439)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iPostgresqlDbUpdate_1Process(aatams_sattag_dm_harvester.java:2152)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iUpdateIndex_1Process(aatams_sattag_dm_harvester.java:1463)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.tPostgresqlConnection_1Process(aatams_sattag_dm_harvester.java:1344)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.runJobInTOS(aatams_sattag_dm_harvester.java:5519)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.main(aatams_sattag_dm_harvester.java:5307)
2017-02-18 00:00:38;DYl8Rc;DYl8Rc;DYl8Rc;8177;AATAMS_SATTAG_DM;aatams_sattag_dm_harvester;_MOp9oJgmEeOMouHqP27dXg;0.1;Default;;begin;;
```

**Comment by jonescc** [comment]
The AATAMS_SATTAG_HARVESTER tJDBC_Input_4 component in HarvestCTDdata uses a schema expecting columns to be returned in a specific order (i.e. ref, PTT, END_DATE, MAX_DBAR, LAT, LON etc), however the select statement used to select the data does not specify the required order ("select * from ctd;").   The order of the columns returned for this file does not match the expected order and so a column which is a string is incorrectly attempted to be converted to a float as per the exception message above.

I'd suggest specifying the required order of the columns in the sql statement used to select the data i.e.

```
"select ref, PTT, END_DATE, MAX_DBAR, LAT, LON, NUM, N_TEMP, " +
" N_COND, N_SAL, TEMP_DBAR, TEMP_VALS, COND_DBAR, COND_VALS, " +
" SAL_DBAR, SAL_VALS, N_FLUORO, FLUORO_DBAR, FLUORO_VALS, N_OXY, " +
" OXY_DBAR, OXY_VALS, QC_PROFILE, QC_TEMP, QC_SAL, SAL_CORRECTED_VALS FROM ctd"
```

**Comment by xhoenner** [comment]
Thanks @jonescc for looking into this. I've compared the problematic file ('ct133.mdb') with another file ('ct101.mdb') and it indeed appears that the tag manufacturer has recently changed the order of the fields within the ctd table. You've just got to love that. 

Now that you've pointed this out I also noticed that they have renamed the "LAT" and "LON" columns to 'lat', 'lon'. Before I implement the change in the tJDBC_Input would you mind double checking that, when reading data using your select statement, Talend could successfully extract 'lat' and 'lon' values even though these fields are now all lowercase?

**Comment by lwgordonimos** [comment]
Generally speaking, Microsoft products are very often *not* case sensitive by default, so it's very plausible that the change in case would have no effect at all if just extracting from the MDB.

**Comment by xhoenner** [comment]
huh, who would have thought? Some will say such leniency adequately highlights Microsoft's lack of rigour in about everything they make.

**Comment by jonescc** [comment]
Yes it ignores case - the first column is actually REF not ref as per the schema.

**Comment by xhoenner** [comment]
Sounds good, too easy then. PR's up --> https://github.com/aodn/harvesters/pull/502

**Comment by jonescc** [comment]
@xhoenner - the updated version has been deployed to rc.  Can you arrange to get this tested there?

**Comment by xhoenner** [comment]
Great. No I can't ssh into any of the IMOS machines from here unfortunately. I'd suggest you download ct133.mdb from 10aws and dump it into $INCOMING_DIR/AATAMS/AATAMS_SATTAG_DM on rc and see whether it gets processed.

Note that you may have to run talend_liqui AATAMS_SATTAG_NRT beforehand as the _DM harvester uses a table in the _nrt schema which may not be present in the rc database.

**Comment by jonescc** [comment]
Issue with changelog running on an empty schema? 

```
INFO 3/8/17 3:26 PM:liquibase: Reading from aatams_sattag_dm.databasechangelog
SEVERE 3/8/17 3:26 PM:liquibase: Change Set changelog.xml::create_unique_index_on_summary_data::xhoenner failed.  Error: Error executing SQL CREATE UNIQUE INDEX unique_summary_data_idx ON summary_data(summary_id): ERROR: relation "summary_data" does not exist
liquibase.exception.DatabaseException: Error executing SQL CREATE UNIQUE INDEX unique_summary_data_idx ON summary_data(summary_id): ERROR: relation "summary_data" does not exist
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:62)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:104)
        at liquibase.database.AbstractDatabase.execute(AbstractDatabase.java:1091)
        at liquibase.database.AbstractDatabase.executeStatements(AbstractDatabase.java:1075)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:317)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:27)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.Liquibase.update(Liquibase.java:114)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iPostgresqlDbUpdate_1Process(aatams_sattag_dm_harvester.java:2081)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.iUpdateIndex_1Process(aatams_sattag_dm_harvester.java:1463)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.tPostgresqlConnection_1Process(aatams_sattag_dm_harvester.java:1344)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.runJobInTOS(aatams_sattag_dm_harvester.java:5519)
        at aatams_sattag_dm.aatams_sattag_dm_harvester_0_1.aatams_sattag_dm_harvester.main(aatams_sattag_dm_harvester.java:5307)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "summary_data" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:395)
        at liquibase.executor.jvm.JdbcExecutor$1ExecuteStatementCallback.doInStatement(JdbcExecutor.java:92)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
        ... 12 more
INFO 3/8/17 3:26 PM:liquibase: Successfully released change log lock
```

**Comment by xhoenner** [comment]
hmm, looks like it's indeed time to use the good old pg_dump/pg_restore trick...

**Comment by jonescc** [comment]
OK, so I copied aatams_sattag_nrt and aatamas_sattag_dm chemas from production and the pipeline now processes the file in rc.  However, looking at the other jdbcinputs you are using, you using 'select *' in Harvest_LocDiveSummaryHauloutData in tJDBCInput_2 and tJDBCInput_5.

Looking at tJDBCInput_2 the source file has extra columns, but not sure whether this is a problem as otherwise the columns match the schema and will be processed.

However for tJDBCInput_5, there is an extra column in the source file which would throw out the source data to talend schema mapping PHOSI_SECS, but does not throw an error.

You should probably always specify the select list you want so an error will be thrown if one can't be found and the mapping will always be performed correctly.   Also if you want to know if any new columns have been added you should probably check for expected columns as you currently check for expected tables in your compliance checks.

So although this runs to completion in RC, I don't think its correctly processing this file and some changes should be made.

**Comment by jonescc** [comment]
Looks to be running OK to me in RC.  Should I promote this to prod?

**Comment by jonescc** [comment]
Actually, failed to build due to "No space left on device"

**Comment by jonescc** [comment]
OK, rebuilt and promoted to RC.  Appears to run OK.
