### ISSUE TITLE
Problem using java.text.SimpleDateFormat.parse

### ISSUE THREAD

**Issue by ggalibert** [aodn/harvesters#753]
There's currently an issue with using `java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1380)` for any new files that goes into ACORN_HOURLY_AVG_QC_harvester. The following errors are output:
```
Traceback (most recent call last):
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/aodncore/pipeline/handlerbase.py", line 1029, in run
    self.trigger(transition['trigger'])
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 33, in get_trigger
    return func(*args, **kwargs)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 283, in trigger
    return self.machine._process(f)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 840, in _process
    return trigger()
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 313, in _trigger
    if t.execute(event_data):
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 195, in execute
    machine._callback(func, event_data)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 823, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/aodncore/pipeline/handlerbase.py", line 778, in _publish
    self._harvest()
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/aodncore/pipeline/handlerbase.py", line 742, in _harvest
    harvest_runner.run(files_to_harvest)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/aodncore/pipeline/steps/harvest.py", line 236, in run
    self.run_additions(addition_map, self.tmp_base_dir)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/aodncore/pipeline/steps/harvest.py", line 379, in run_additions
    self.execute_talend(harvester_command, event.matched_files, talend_base_dir)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/aodncore/pipeline/steps/harvest.py", line 292, in execute_talend
    p.execute()
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/aodncore/util/process.py", line 77, in execute
    stderr=self.stdout_text))
SystemCommandFailedError: system command exited with an error, output is INFO 6/3/19 11:39 AM:liquibase: Successfully acquired change log lock
INFO 6/3/19 11:39 AM:liquibase: Reading from acorn_hourly_avg_qc.databasechangelog
INFO 6/3/19 11:39 AM:liquibase: Reading from acorn_hourly_avg_qc.databasechangelog
INFO 6/3/19 11:39 AM:liquibase: Successfully released change log lock
Start of try block
tempFile_cid /tmp/talend-temp-1773312720566781490/changelog.xml
***********************
conn host:dbprod.emii.org.au, port:5432, schema:acorn_hourly_avg_qc, name:harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory, user:acorn_hourly_avg_qc
url_cid:jdbc:postgresql://dbprod.emii.org.au:5432/harvest?loginTimeout=1000&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
schema_cid:acorn_hourly_avg_qc
userName_cid:acorn_hourly_avg_qc
INFO 6/3/19 11:39 AM:liquibase: Successfully acquired change log lock
INFO 6/3/19 11:39 AM:liquibase: Reading from acorn_hourly_avg_qc.databasechangelog
INFO 6/3/19 11:39 AM:liquibase: Reading from acorn_hourly_avg_qc.databasechangelog
INFO 6/3/19 11:39 AM:liquibase: Successfully released change log lock
***** completed finally block ***********
In finally block
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in component tMap_1
java.lang.NullPointerException
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1380)
	at java.text.DateFormat.parse(DateFormat.java:355)
	at routines.TalendDate.parseDate(TalendDate.java:763)
	at acorn_hourly_avg_qc.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iNetCDFGlobalAttributes_1Process(HarvestTimeseriesFile.java:1380)
	at acorn_hourly_avg_qc.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlRow_1Process(HarvestTimeseriesFile.java:808)
	at acorn_hourly_avg_qc.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.tPostgresqlConnection_1Process(HarvestTimeseriesFile.java:679)
	at acorn_hourly_avg_qc.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.iIncludeSdiLibraries_1Process(HarvestTimeseriesFile.java:556)
	at acorn_hourly_avg_qc.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJobInTOS(HarvestTimeseriesFile.java:3691)
	at acorn_hourly_avg_qc.harvesttimeseriesfile_0_1.HarvestTimeseriesFile.runJob(HarvestTimeseriesFile.java:3540)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iNewOrModifiedFileList_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1813)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iDeletedFileList_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1600)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iPostgresqlDbUpdate_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1276)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iUpdateIndex_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1058)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.runJobInTOS(ACORN_HOURLY_AVG_QC_harvester.java:3649)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.main(ACORN_HOURLY_AVG_QC_harvester.java:3485)
Exception in component tRunJob_3
java.lang.RuntimeException: Child job running failed
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iNewOrModifiedFileList_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1824)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iDeletedFileList_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1600)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iPostgresqlDbUpdate_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1276)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.iUpdateIndex_1Process(ACORN_HOURLY_AVG_QC_harvester.java:1058)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.runJobInTOS(ACORN_HOURLY_AVG_QC_harvester.java:3649)
	at acorn_hourly_avg_qc.acorn_hourly_avg_qc_harvester_1_0.ACORN_HOURLY_AVG_QC_harvester.main(ACORN_HOURLY_AVG_QC_harvester.java:3485)
```

See file in `/mnt/ebs/error/ACORN_DM`.

**Comment by lbesnard** [comment]
@ggalibert the fix is simple. 

The harvester needs a global attribute called time_coverage_start to use as the time value and this is missing from the files

the only gatts are
```
                :project = "Integrated Marine Observing System (IMOS)" ;
                :Conventions = "CF-1.6,IMOS-1.4" ;
                :institution = "Australian Coastal Ocean Radar Network (ACORN)" ;
                :title = "IMOS ACORN Turqoise Coast (TURQ), one hour averaged current RT-QC data, 2009-03-27T09:00:00Z" ;
                :instrument = "CODAR Ocean Sensors/SeaSonde" ;
                :site_code = "TURQ, Turqoise Coast" ;
                :ssr_Stations = "Seabird (SBRD), Cervantes (CRVT)" ;
                :date_created = "2019-06-04T04:34:55Z" ;

```

**Comment by ggalibert** [comment]
Thanks,

can you please check the differnce between simone's recently processed file and the ones we currently have and then highlight the difference in this [discussion](https://github.com/aodn/content/issues/309) for Simone to take into account.
